services:
  ocr-server:
    image: hertzg/tesseract-server
    container_name: ocr-server
    ports:
      - "8884:8884"
    environment:
      - HTTP_LISTEN_ADDRESS=0.0.0.0
      - HTTP_LISTEN_PORT=8884
      - HTTP_OUTPUT_JSON_SPACES=2 # Pretty print JSON, 2 spaces instead of 0
    restart: unless-stopped

  ocr-web:
    image: nginx:alpine
    container_name: ocr-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ocr-server
    restart: unless-stopped
