services:
  ocr-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ocr-api
    # Host mode required for paddle downloading models.
    # I was not able to identify which port is needed to download the models.
    network_mode: "host"
    # ports:
    #   - "8884:8884"
    volumes:
      - ocr-api_model-cache:/root/.paddleocr/whl
    restart: unless-stopped

  ocr-web:
    image: nginx:alpine
    container_name: ocr-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ocr-api
    restart: unless-stopped

volumes:
  ocr-api_model-cache:
